### PR TITLE
consolidate rules using macros and make it compatible with the base policy versions without the respecitve macros

### PR DESCRIPTION
**Pull request by sopos**

### CODE REVIEW

**Comment by sopos** [comment]
I've checked the generated policy difference for el8:
```
@@ -50,0 +51,2 @@
+(typeattributeset cil_gen_require filesystem_type)
+(typeattributeset cil_gen_require mountpoint)
```

and el9:
```
@@ -68,3 +67,0 @@
-(typeattributeset cil_gen_require boot_t)
-(typeattributeset cil_gen_require home_root_t)
-(typeattributeset cil_gen_require root_t)
@@ -72 +68,0 @@
-(typeattributeset cil_gen_require dosfs_t)
@@ -82 +77,0 @@
-(typeattributeset cil_gen_require user_tmp_t)
@@ -94 +89,4 @@
-(allow fapolicyd_t file_type (dir (watch_mount watch_with_perm)))
+(allow fapolicyd_t file_type (dir (getattr open search)))
+(allow fapolicyd_t file_type (dir (getattr watch_mount)))
+(allow fapolicyd_t file_type (dir (getattr open search)))
+(allow fapolicyd_t file_type (dir (getattr watch_with_perm)))
@@ -97 +95,2 @@
-(allow fapolicyd_t mountpoint (dir (watch_sb)))
+(allow fapolicyd_t mountpoint (dir (getattr open search)))
+(allow fapolicyd_t mountpoint (dir (getattr watch_sb)))
@@ -160,8 +158,0 @@
-(allow fapolicyd_t boot_t (dir (getattr watch_mount)))
-(allow fapolicyd_t boot_t (dir (getattr watch_with_perm)))
-(allow fapolicyd_t tmp_t (dir (getattr watch_mount)))
-(allow fapolicyd_t tmp_t (dir (getattr watch_with_perm)))
-(allow fapolicyd_t home_root_t (dir (getattr watch_mount)))
-(allow fapolicyd_t home_root_t (dir (getattr watch_with_perm)))
-(allow fapolicyd_t root_t (dir (getattr watch_mount)))
-(allow fapolicyd_t root_t (dir (getattr watch_with_perm)))
@@ -169,8 +159,0 @@
-(allow fapolicyd_t tmpfs_t (dir (getattr open search)))
-(allow fapolicyd_t tmpfs_t (dir (getattr watch_mount)))
-(allow fapolicyd_t tmpfs_t (dir (getattr open search)))
-(allow fapolicyd_t tmpfs_t (dir (getattr watch_with_perm)))
-(allow fapolicyd_t dosfs_t (dir (getattr open search)))
-(allow fapolicyd_t dosfs_t (dir (getattr watch_mount)))
-(allow fapolicyd_t dosfs_t (dir (getattr open search)))
-(allow fapolicyd_t dosfs_t (dir (getattr watch_with_perm)))
@@ -198,4 +180,0 @@
-(allow fapolicyd_t user_tmp_t (dir (getattr open search)))
-(allow fapolicyd_t user_tmp_t (dir (getattr watch_mount)))
-(allow fapolicyd_t user_tmp_t (dir (getattr open search)))
-(allow fapolicyd_t user_tmp_t (dir (getattr watch_with_perm)))
@@ -262,2 +241,7 @@
-    (allow fapolicyd_t rpm_var_lib_t (file (create)))
-    (allow fapolicyd_t rpm_var_lib_t (dir (write add_name)))
+    (allow fapolicyd_t var_t (dir (getattr open search)))
+    (allow fapolicyd_t var_lib_t (dir (getattr open search)))
+    (allow fapolicyd_t rpm_var_lib_t (dir (ioctl read write getattr lock open add_name remove_name search)))
+    (allow fapolicyd_t rpm_var_lib_t (file (ioctl read write create getattr setattr lock append unlink link rename open watch watch_reads)))
+    (allow fapolicyd_t rpm_var_lib_t (dir (ioctl read write getattr lock open add_name remove_name search)))
+    (allow fapolicyd_t rpm_var_lib_t (lnk_file (ioctl read write create getattr setattr lock append unlink link rename watch watch_reads)))
+    (allow fapolicyd_t rpm_var_lib_t (file (map)))
```

all the specific `watch_mount` and `watch_with_perm` are covered with the
```
(allow fapolicyd_t file_type (dir (getattr watch_mount)))
(allow fapolicyd_t file_type (dir (getattr watch_with_perm)))
```

The additional rpm_var_lib_t rules comes probably form the build system's base policy macros. The change does not touch anything like that.

**Comment by sopos** [comment]
After the merge I suggest to tag it with v0.6 and create the respective release as well.

**Comment by sopos** [comment]
@zpytela, could you take a look and confirm my conclusion on the diff above?

**Comment by zpytela** [comment]
I can confirm the 2 allow rules using the `file_type` attribute are a superset for individual types, but note it is only for the `dir` class. Not sure what was the assessment request exactly for.

**Comment by zpytela** [comment]
LGTM at first sight, but frankly I'd use expanded policy or some tool for comparison of the resulting policy rules.

**Pull request merged**
